name: Sciris CI tests
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  install_and_test:
    timeout-minutes: 8
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: [ '3.9', '3.10', '3.11' '3.12' ]
    runs-on: ${{ matrix.os }}
    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Sciris
        run: pip install -e .
      - name: Install tests
        working-directory: ./tests
        run: pip install -r requirements.txt
      - name: Run API tests
        working-directory: ./tests
        run: pytest --durations=0 --junitxml=test-results.xml # Run actual tests
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_results
          path: tests/test-results.xml
